### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by mcollina** [nearform/fastify-secrets-azure#21]
The tests in CI are not currently passing

**Comment by simoneb** [comment]
somebody removed the vault we're using from the azure account, most likely

**Comment by simoneb** [comment]
to solve this issue:

- reach out to @efrisby to ask to create a new vault in a way that it won't get deleted
- configure the new vault credentials in CI via secrets

**Comment by nigelhanlon** [comment]
CI is now passing again and all dependabot updates have been applied. The vault needed for the integration test has been recreated.
