### ISSUE TITLE
CI intermittently failing

### ISSUE THREAD

**Issue by simoneb** [nearform/fastify-secrets-azure#70]
CI is intermittently failing on master, see for example https://github.com/nearform/fastify-secrets-azure/runs/2543746325?check_suite_focus=true.

There is a chance we're not using tap correctly, as the error seems to come from there. Or maybe a timeout? Something to look at to make it more reliable.

**Comment by gilach** [comment]
For future reference: tap cli --timeout argument sets the timeout threshold for a whole test file, not a single test, so even you there is a `setTimeout` call within the test body it still can fail even the timeout for a whole file is shorter than the amount set inside the test.
